# Generated by Django 3.0.7 on 2020-06-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.IntegerField()),
                ('receiver', models.IntegerField()),
                ('message', models.TextField()),
                ('subject', models.CharField(max_length=1000)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
